from .choices.colors import COLORS
from backend.listings import models
from .choices.body_type_choices import BODY_TYPE_CHOICES


class Car(models.Model):
    # ...
    color = models.CharField(max_length=10, choices=[(c[0], c[1]) for c in COLORS])
    # ...
class Car(models.Model):
    # ...
    body_type = models.CharField(max_length=10, choices=[(c[0], c[1]) for c in BODY_TYPE_CHOICES])
    # ...