# Generated by Django 5.0.3 on 2024-03-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.Notification(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auto_parks',
            },
        ),
    ]
