# Generated by Django A.B on YYYY-MM-DD HH:MM

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('consumer', 'previous_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # other fields here
            ],
        ),
    ]
